import fs from "fs/promises";
import path from "path";
import { listTests, readLastRun } from "./storage.js";

export interface ReportOptions {
  days: number;
  out?: string;
}

interface RunRow {
  name: string;
  passed: boolean;
  ranAt: string;
  durationMs: number;
  prompt: string;
  url: string;
}

export async function runReport(opts: ReportOptions): Promise<{ markdown: string; stats: Stats }> {
  const tests = await listTests();
  const since = new Date(Date.now() - opts.days * 24 * 60 * 60 * 1000);

  const rows: RunRow[] = [];
  for (const t of tests) {
    const lastRun = await readLastRun(t.name);
    if (!lastRun) continue;
    const ran = new Date(lastRun.ranAt);
    if (ran < since) continue;
    rows.push({
      name: t.name,
      passed: lastRun.passed,
      ranAt: lastRun.ranAt,
      durationMs: lastRun.durationMs,
      prompt: t.prompt,
      url: t.url,
    });
  }

  rows.sort((a, b) => b.ranAt.localeCompare(a.ranAt));

  const stats = computeStats(rows, tests.length);
  const markdown = renderMarkdown(rows, stats, opts.days);

  if (opts.out) {
    await fs.writeFile(opts.out, markdown);
  }

  return { markdown, stats };
}

interface Stats {
  totalTests: number;
  runsInWindow: number;
  passed: number;
  failed: number;
  passRatePct: number;
  avgDurationMs: number;
  testsWithoutRecentRun: number;
}

function computeStats(rows: RunRow[], totalTests: number): Stats {
  const passed = rows.filter((r) => r.passed).length;
  const failed = rows.length - passed;
  const avg = rows.length > 0 ? rows.reduce((s, r) => s + r.durationMs, 0) / rows.length : 0;
  return {
    totalTests,
    runsInWindow: rows.length,
    passed,
    failed,
    passRatePct: rows.length > 0 ? (passed / rows.length) * 100 : 0,
    avgDurationMs: avg,
    testsWithoutRecentRun: totalTests - rows.length,
  };
}

function renderMarkdown(rows: RunRow[], stats: Stats, days: number): string {
  const lines: string[] = [];
  lines.push(`# 🤖 Promptomate Weekly Report`);
  lines.push("");
  lines.push(`Window: last ${days} day${days > 1 ? "s" : ""} · Generated ${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC`);
  lines.push("");
  lines.push(`## Summary`);
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|---|---:|`);
  lines.push(`| Total saved tests | ${stats.totalTests} |`);
  lines.push(`| Runs in window | ${stats.runsInWindow} |`);
  lines.push(`| Passed | ${stats.passed} |`);
  lines.push(`| Failed | ${stats.failed} |`);
  lines.push(`| Pass rate | ${stats.passRatePct.toFixed(1)}% |`);
  lines.push(`| Avg duration | ${(stats.avgDurationMs / 1000).toFixed(1)}s |`);
  lines.push(`| Not run in window | ${stats.testsWithoutRecentRun} |`);
  lines.push("");

  if (rows.length === 0) {
    lines.push(`_No runs in the last ${days} day${days > 1 ? "s" : ""}. Try \`promptomate ci\` to execute the full suite._`);
    lines.push("");
    return lines.join("\n");
  }

  lines.push(`## Results`);
  lines.push("");
  lines.push(`| Test | Status | Duration | Last run |`);
  lines.push(`|---|---|---:|---|`);
  for (const r of rows) {
    const icon = r.passed ? "✅" : "❌";
    const dur = `${(r.durationMs / 1000).toFixed(1)}s`;
    const when = r.ranAt.slice(0, 16).replace("T", " ");
    lines.push(`| \`${r.name}\` | ${icon} ${r.passed ? "passed" : "failed"} | ${dur} | ${when} |`);
  }
  lines.push("");

  const failing = rows.filter((r) => !r.passed);
  if (failing.length > 0) {
    lines.push(`## Failing tests — action needed`);
    lines.push("");
    for (const f of failing) {
      lines.push(`### ${f.name}`);
      lines.push(`- **Scenario**: ${f.prompt}`);
      lines.push(`- **URL**: ${f.url}`);
      lines.push(`- **Last run**: ${f.ranAt.slice(0, 16).replace("T", " ")}`);
      lines.push(`- **Next step**: \`promptomate triage ${f.name} --apply\``);
      lines.push("");
    }
  }

  lines.push(`---`);
  lines.push(`_Generated by [Promptomate](https://github.com/guttaashok1/promptomate). Pipe this into email/Slack/PagerDuty via your scheduler._`);
  lines.push("");

  return lines.join("\n");
}
